# Dockerfile for React Frontend
FROM node:18-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY ./package*.json ./

RUN npm install


# Expose the port the app runs on
EXPOSE 3000

# Start the app
CMD ["npm", "start"]
