version: "3.8"

services:
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    command:
      - --accounts=10
      - --defaultBalanceEther=1000
      - --gasLimit=12000000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app 
    depends_on:
      - ganache
    environment:
      - REACT_APP_GANACHE_URL=http://ganache:8545
      - CHOKIDAR_USEPOLLING=true

  blockchain:
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    volumes:
      - ./blockchain:/app
      - ./frontend/src/contracts:/app/frontend/src/contracts  # <-- Add this

    depends_on:
      - ganache
    entrypoint: sh
    tty: true